---
title: "R Notebook"
output: html_notebook
---

4 ways to aggregate!!!

```{r}
testdata <- data_raw %>% 
    select(Metadata_PlateID, Metadata_WellID, starts_with("Median"))

system.time(expr = {
a <- aggregate(testdata[,3:ncol(testdata)], by = list(testdata$Metadata_PlateID, testdata$Metadata_WellID), FUN = median, na.rm = TRUE)
})
```

```{r}
system.time(expr = {
b <- testdata %>%
  select(Metadata_PlateID, Metadata_WellID, starts_with("Median")) %>%
  group_by(Metadata_PlateID, Metadata_WellID) %>%
  summarise_at(vars(starts_with("Median")), funs(med = median(., na.rm = TRUE)))
})
```

```{r}
system.time(expr = {
c <- testdata[ , lapply(.SD, function(x) median(x, na.rm = TRUE)),
          by = .(Metadata_PlateID, Metadata_WellID)]
})


```

When you know the length of each group!!!!

```{r}
summarise_PerWell <- function(
  df,               # the df of raw (per image) data
  no_images,        # the number of images taken per well
  filtered = FALSE  # logical indicating whether poor quality images have been filtered
){
  
  # check function inputs
  
  assertthat::assert_that(dim(df)[1] %% no_images == 0,
                          msg = "Check that the number of rows in 'df' is a multiple of 'no_images'")
  
  
  assertthat::assert_that(is.numeric(no_images),
                          length(no_images) == 1,
                          msg = "Check 'no_images' is single number")
  
  
  # obtain only count columns
  df_count <- df %>% 
    select(starts_with("Count")) 
  
  # take sum of every 'no_images' rows to get per well data
  
  mat_sum <- apply(df_count, 2, 
             function(x) colSums(matrix(x, nrow = no_images)))
  
  # obtain only median columns
  df_median <- df %>% 
    select(starts_with("Median")) 
  
  # take median of every 'no_images' rows to get per well data
  
  mat_median <- apply(df_median, 2, 
                      function(x) colMedians(matrix(x, nrow = no_images)))
  
  # get metadata rows, 1 for each well
  df_meta <- df %>%
    select(Metadata_PlateID, Metadata_WellID)
  
  nrow <- dim(df)[1]
  repeats <- nrow/no_images
    
  df_meta <- df_meta[ rep(c(TRUE, rep(FALSE, no_images - 1)), 
                          repeats), ]
  
  # join summarised matrices
  full_mat <- cbind(mat_sum, mat_median)
  
  df_full <- cbind(df_meta, as.data.frame(full_mat))
  
  return(df_full)
  
}
```
